spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  application:
    name: REST-API-Java16

server:
  port: 8080