spring.application.name=REST-API-Java16

spring.datasource.url=jdbc:postgresql://localhost:5454/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


